var MASTERS_OF_BATTLE = MASTERS_OF_BATTLE || {};

/*
 * 
 */
MASTERS_OF_BATTLE.Constants.BATTLE_FIELD_CELL_SIZE = 50;
MASTERS_OF_BATTLE.Constants.BATTLE_FIELD_CELLS_COLUMNS = 12;
MASTERS_OF_BATTLE.Constants.BATTLE_FIELD_CELLS_ROWS = 9;

MASTERS_OF_BATTLE.Constants.ZINDEX_BATTLE_FIELD = -1;
MASTERS_OF_BATTLE.Constants.ZINDEX_BATTLE_FIELD_CELL = 10;
MASTERS_OF_BATTLE.Constants.ZINDEX_UNIT = 100;

/*
 * faction
 */
MASTERS_OF_BATTLE.Constants.Faction.HUMAN = 1;
MASTERS_OF_BATTLE.Constants.Faction.UNDEAD = 0;

/*
 * game arbitration
 */
MASTERS_OF_BATTLE.Constants.GameArbitration = [];
MASTERS_OF_BATTLE.Constants.GameArbitration.State = {
	INITIALIZING_GAME:10,
	INFORMING_NEXT_PLAYER_TO_MOVE:15,
	WAITING_FOR_PLAYER_MOVE:20,
	APPLYING_PLAYER_MOVE:25,
	WAITING_FOR_ANIMATIONS_TO_FINISH:30,
	GAME_ENDED:40
};

